### PR TITLE
Add support for cloudflare_page_rules

### PR DESCRIPTION
**Pull request by gvwirth**
This PR adds support for generating and importing cloudflare_page_rule resources. 

The main change is pulling the nesting logic out into a function and recursively calling it in order to add further nested blocks into the Terraform output.

There is also a minor bug fix to not allow account_id and zone_id to be set concurrently.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
I appreciate you putting this together :) It's been on my radar for a
little while but I've been occupied some other work to give it the time
it deserves. I'll need a few days to go through this and make sure we're
not introducing any regressions with this refactor but hopefully
sometime next week I'll have time for review.

**Comment by jacobbednarz** [comment]
Trying this out on a fairly complex page rule is looking about 90% of the way there.

VvJZVNHI-QhMMzhCo-CiPX41hA

And the debug output

```
DEBU[0022] reading Terraform schema for Cloudflare provider
DEBU[0024] beginning to read and build cloudflare_page_rule resources
DEBU[0025] got unknown attribute configuration: key zone_id, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key ignore, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key codes, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key ttl, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key always_use_https, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key automatic_https_rewrites, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key browser_check, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key bypass_cache_on_cookie, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key cache_by_device_type, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key cache_deception_armor, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key cache_level, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key cache_on_cookie, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key disable_apps, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key disable_performance, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key disable_railgun, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key disable_security, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key edge_cache_ttl, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key email_obfuscation, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key explicit_cache_control, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key ip_geolocation, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key mirage, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key opportunistic_encryption, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key origin_error_page_pass_thru, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key polish, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key resolve_override, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key respect_strong_etag, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key response_buffering, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key rocket_loader, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key security_level, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key server_side_exclude, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key sort_query_string_for_cache, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key ssl, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key true_client_ip_header, value <nil>, value type <nil>
DEBU[0025] got unknown attribute configuration: key waf, value <nil>, value type <nil>
resource "cloudflare_page_rule" "terraform_managed_resource_8a3461ca5d3cc6c27135b7b0d91f865c" {
  priority = 1
  status = "active"
  target = "example.terraform.cfapi.net/*"
  actions {
    cache_key_fields {
      header {
        include = [ "authorization" ]
      }
      host {
        resolved = true
      }
      query_string {
        exclude = [ "_guid" ]
      }
      user {
        device_type = true
        geo = true
        lang = false
      }
    }
    always_online = "on"
    browser_cache_ttl = 1800
    host_header_override = "not-example.com"
  }
}
```

By the looks of things, the cache by status is missing. I also suspect there may be some manual mapping to do for the `custom_cache_key` values as we have some [easier to understand mappings in the Terraform provider](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_page_rule.go#L743-L760).

**Comment by jacobbednarz** [comment]
Other than the above, I think we're nearly there! I played with a few other configurations and they all looked like they were working. It will be great to have this available for use ⭐

**Comment by gvwirth** [comment]
Awesome! I'll dig in a bit on your findings today and see if I can work it out. This is a great tool and I'd love to help get it closer to supporting all resource types.

**Comment by jacobbednarz** [comment]
Sorry it's taken so long to get back to this; been pretty busy! It looks like there is still a failing test.

```
$ CLOUDFLARE_TERRAFORM_INSTALL_PATH="/Users/jacob/src/scratch" make test

?   	github.com/cloudflare/cf-terraforming/cmd/cf-terraforming	[no test files]
=== RUN   TestGenerate_writeAttrLine
=== RUN   TestGenerate_writeAttrLine/value_is_nil
=== RUN   TestGenerate_writeAttrLine/value_is_string
=== RUN   TestGenerate_writeAttrLine/value_is_bool
=== RUN   TestGenerate_writeAttrLine/depth_is_0
=== RUN   TestGenerate_writeAttrLine/depth_is_6
=== RUN   TestGenerate_writeAttrLine/value_is_int
=== RUN   TestGenerate_writeAttrLine/value_is_float
=== RUN   TestGenerate_writeAttrLine/value_is_list_of_strings
=== RUN   TestGenerate_writeAttrLine/value_is_block_of_strings
--- PASS: TestGenerate_writeAttrLine (0.00s)
    --- PASS: TestGenerate_writeAttrLine/value_is_nil (0.00s)
    --- PASS: TestGenerate_writeAttrLine/value_is_string (0.00s)
    --- PASS: TestGenerate_writeAttrLine/value_is_bool (0.00s)
    --- PASS: TestGenerate_writeAttrLine/depth_is_0 (0.00s)
    --- PASS: TestGenerate_writeAttrLine/depth_is_6 (0.00s)
    --- PASS: TestGenerate_writeAttrLine/value_is_int (0.00s)
    --- PASS: TestGenerate_writeAttrLine/value_is_float (0.00s)
    --- PASS: TestGenerate_writeAttrLine/value_is_list_of_strings (0.00s)
    --- PASS: TestGenerate_writeAttrLine/value_is_block_of_strings (0.00s)
=== RUN   TestGenerate_ResourceNotSupported
--- PASS: TestGenerate_ResourceNotSupported (17.42s)
=== RUN   TestResourceGeneration
=== RUN   TestResourceGeneration/cloudflare_worker_route
=== RUN   TestResourceGeneration/cloudflare_access_IdP_OTP_(account)
=== RUN   TestResourceGeneration/cloudflare_BYO_IP_prefix
=== RUN   TestResourceGeneration/cloudflare_certificate_pack
=== RUN   TestResourceGeneration/cloudflare_custom_pages_(account)
=== RUN   TestResourceGeneration/cloudflare_custom_hostname
=== RUN   TestResourceGeneration/cloudflare_WAF_override
=== RUN   TestResourceGeneration/cloudflare_argo_tunnel
=== RUN   TestResourceGeneration/cloudflare_record_subdomain
=== RUN   TestResourceGeneration/cloudflare_access_rule_(account)
=== RUN   TestResourceGeneration/cloudflare_custom_hostname_fallback_origin
=== RUN   TestResourceGeneration/cloudflare_firewall_rule
=== RUN   TestResourceGeneration/cloudflare_record_simple
=== RUN   TestResourceGeneration/cloudflare_access_application_simple_(account)
=== RUN   TestResourceGeneration/cloudflare_access_application_with_CORS_(account)
=== RUN   TestResourceGeneration/cloudflare_access_IdP_OAuth_(zone)
=== RUN   TestResourceGeneration/cloudflare_filter
=== RUN   TestResourceGeneration/cloudflare_health_check
=== RUN   TestResourceGeneration/cloudflare_spectrum_application
=== RUN   TestResourceGeneration/cloudflare_custom_pages_(zone)
=== RUN   TestResourceGeneration/cloudflare_origin_CA_certificate
=== RUN   TestResourceGeneration/cloudflare_access_IdP_OTP_(zone)
=== RUN   TestResourceGeneration/cloudflare_account_member
=== RUN   TestResourceGeneration/cloudflare_load_balancer
=== RUN   TestResourceGeneration/cloudflare_load_balancer_monitor
=== RUN   TestResourceGeneration/cloudflare_logpush_jobs
=== RUN   TestResourceGeneration/cloudflare_zone_lockdown
=== RUN   TestResourceGeneration/cloudflare_access_IdP_OAuth_(account)
=== RUN   TestResourceGeneration/cloudflare_access_rule_(zone)
=== RUN   TestResourceGeneration/cloudflare_record_CAA
=== RUN   TestResourceGeneration/cloudflare_workers_kv_namespace
=== RUN   TestResourceGeneration/cloudflare_page_rule
    generate_test.go:169:
        	Error Trace:	generate_test.go:169
        	Error:      	Not equal:
        	            	expected: "resource \"cloudflare_page_rule\" \"terraform_managed_resource\" {\n  priority = 1\n  status = \"active\"\n  target = \"*example.com/images/*\"\n  zone_id = \"0da42c8d2132a9ddaf714f9e7c920711\"\n  actions {\n    cache_key_fields {\n      cookie {\n        check_presence = [ \"x-some-header\" ]\n        include = [ \"x-some-other-header\", \"x-some-value\" ]\n      }\n      header {\n        check_presence = [ \"x-forwarded-for\" ]\n        include = [ \"authorization\" ]\n      }\n      host {\n        resolved = true\n      }\n      query_string {\n        exclude = [ \"*\" ]\n      }\n      user {\n        device_type = true\n        geo = true\n        lang = false\n      }\n    }\n    cache_ttl_by_status {\n      codes = \"200\"\n      ttl = 60\n    }\n    cache_ttl_by_status {\n      codes = \"204\"\n      ttl = -1\n    }\n    cache_ttl_by_status {\n      codes = \"300-399\"\n      ttl = 0\n    }\n    browser_cache_ttl = 1800\n    host_header_override = \"not-example.com\"\n  }\n}"
        	            	actual  : "resource \"cloudflare_page_rule\" \"terraform_managed_resource\" {\n  priority = 1\n  status = \"active\"\n  target = \"*example.com/images/*\"\n  zone_id = \"0da42c8d2132a9ddaf714f9e7c920711\"\n  actions {\n    cache_key_fields {\n      cookie {\n        check_presence = [ \"x-some-header\" ]\n        include = [ \"x-some-other-header\", \"x-some-value\" ]\n      }\n      header {\n        check_presence = [ \"x-forwarded-for\" ]\n        include = [ \"authorization\" ]\n      }\n      host {\n        resolved = true\n      }\n      query_string {\n        exclude = [ \"*\" ]\n      }\n      user {\n        device_type = true\n        geo = true\n        lang = false\n      }\n    }\n    cache_ttl_by_status {\n      codes = \"300-399\"\n      ttl = 0\n    }\n    cache_ttl_by_status {\n      codes = \"200\"\n      ttl = 60\n    }\n    cache_ttl_by_status {\n      codes = \"204\"\n      ttl = -1\n    }\n    browser_cache_ttl = 1800\n    host_header_override = \"not-example.com\"\n  }\n}"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -28,2 +28,6 @@
        	            	     cache_ttl_by_status {
        	            	+      codes = "300-399"
        	            	+      ttl = 0
        	            	+    }
        	            	+    cache_ttl_by_status {
        	            	       codes = "200"
        	            	@@ -35,6 +39,2 @@
        	            	     }
        	            	-    cache_ttl_by_status {
        	            	-      codes = "300-399"
        	            	-      ttl = 0
        	            	-    }
        	            	     browser_cache_ttl = 1800
        	Test:       	TestResourceGeneration/cloudflare_page_rule
--- FAIL: TestResourceGeneration (477.22s)
    --- PASS: TestResourceGeneration/cloudflare_worker_route (14.32s)
    --- PASS: TestResourceGeneration/cloudflare_access_IdP_OTP_(account) (13.84s)
    --- PASS: TestResourceGeneration/cloudflare_BYO_IP_prefix (14.32s)
    --- PASS: TestResourceGeneration/cloudflare_certificate_pack (18.88s)
    --- PASS: TestResourceGeneration/cloudflare_custom_pages_(account) (19.19s)
    --- PASS: TestResourceGeneration/cloudflare_custom_hostname (13.44s)
    --- PASS: TestResourceGeneration/cloudflare_WAF_override (14.13s)
    --- PASS: TestResourceGeneration/cloudflare_argo_tunnel (14.19s)
    --- PASS: TestResourceGeneration/cloudflare_record_subdomain (14.19s)
    --- PASS: TestResourceGeneration/cloudflare_access_rule_(account) (14.28s)
    --- PASS: TestResourceGeneration/cloudflare_custom_hostname_fallback_origin (14.01s)
    --- PASS: TestResourceGeneration/cloudflare_firewall_rule (14.14s)
    --- PASS: TestResourceGeneration/cloudflare_record_simple (14.29s)
    --- PASS: TestResourceGeneration/cloudflare_access_application_simple_(account) (14.04s)
    --- PASS: TestResourceGeneration/cloudflare_access_application_with_CORS_(account) (19.65s)
    --- PASS: TestResourceGeneration/cloudflare_access_IdP_OAuth_(zone) (14.27s)
    --- PASS: TestResourceGeneration/cloudflare_filter (14.37s)
    --- PASS: TestResourceGeneration/cloudflare_health_check (13.95s)
    --- PASS: TestResourceGeneration/cloudflare_spectrum_application (19.03s)
    --- PASS: TestResourceGeneration/cloudflare_custom_pages_(zone) (14.41s)
    --- PASS: TestResourceGeneration/cloudflare_origin_CA_certificate (14.54s)
    --- PASS: TestResourceGeneration/cloudflare_access_IdP_OTP_(zone) (14.61s)
    --- PASS: TestResourceGeneration/cloudflare_account_member (14.69s)
    --- PASS: TestResourceGeneration/cloudflare_load_balancer (14.39s)
    --- PASS: TestResourceGeneration/cloudflare_load_balancer_monitor (15.18s)
    --- PASS: TestResourceGeneration/cloudflare_logpush_jobs (13.94s)
    --- PASS: TestResourceGeneration/cloudflare_zone_lockdown (13.64s)
    --- PASS: TestResourceGeneration/cloudflare_access_IdP_OAuth_(account) (13.76s)
    --- PASS: TestResourceGeneration/cloudflare_access_rule_(zone) (13.84s)
    --- PASS: TestResourceGeneration/cloudflare_record_CAA (17.97s)
    --- PASS: TestResourceGeneration/cloudflare_workers_kv_namespace (13.89s)
    --- FAIL: TestResourceGeneration/cloudflare_page_rule (13.83s)
FAIL
FAIL	github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd	495.196s
FAIL
make: *** [test] Error 1
```

**Comment by gvwirth** [comment]
Ah good catch! The tests were passing for me, but as I re-ran them, it would indeed occasionally fail. I sorted the cache_ttl_by_status field by the "codes" attribute, and that seems to take care of it.

**Comment by jacobbednarz** [comment]
thanks again, we're all green here now!

**Pull request merged**
