### PR TITLE
force fw rules to be applied in the order they come from the api

### PR DESCRIPTION
**Pull request by jafowler**
Before:
```
resource "cloudflare_firewall_rule" "terraform_managed_resource_02a15fb6d0c64d858f3b6e1854dbbcaa" {
  action = "allow"
  description = "one"
  filter_id = "75069dc11d89f959bc05ed625a2a7db3"
  paused = false
  zone_id = "5cc4b77b5813aaf2f4262fd5ff61571f"
}
resource "cloudflare_firewall_rule" "terraform_managed_resource_bf45151c7be14ae4ba135611699b29f1" {
  action      = "allow"
  description = "two"
  filter_id   = "b5bafbcc542bd3ed254c1f0969e4fd21"
  paused      = false
  zone_id     = "5cc4b77b5813aaf2f4262fd5ff61571f"
}
```

After:
```
resource "cloudflare_firewall_rule" "terraform_managed_resource_02a15fb6d0c64d858f3b6e1854dbbcaa" {
  action      = "allow"
  description = "one"
  filter_id   = "75069dc11d89f959bc05ed625a2a7db3"
  paused      = false
  zone_id     = "5cc4b77b5813aaf2f4262fd5ff61571f"
}

resource "cloudflare_firewall_rule" "terraform_managed_resource_bf45151c7be14ae4ba135611699b29f1" {
  depends_on  = [cloudflare_firewall_rule.terraform_managed_resource_02a15fb6d0c64d858f3b6e1854dbbcaa]
  action      = "allow"
  description = "two"
  filter_id   = "b5bafbcc542bd3ed254c1f0969e4fd21"
  paused      = false
  zone_id     = "5cc4b77b5813aaf2f4262fd5ff61571f"
}
```

### CODE REVIEW

**Review by jacobbednarz — COMMENTED** [review]
I don’t think using the `depends_on` meta attribute is appropriate here. By default, the firewall rules that [don’t come back with a priority are processed _after_ those that do](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/firewall_rule#priority). With this change, we are disregarding that logic and forcing our own lexical ordering in Terraform. 

I’d first like to see whether the priority field is meant to be used (and we’re missing it somewhere) or whether we simply need to use an ordered map instead of this as introduces an explicit ordering and relationships in the Terraform runner which may have unintended side effects.

**Comment by jafowler** [comment]
Thanks for taking the time to comment @jacobbednarz ! Some things we've noticed in our testing was that even when the API returned in the correct order (element 1 is the first firewall rule that shows up in the UI) after the apply, the order in which they get applied seemed to be arbitrary, meaning rule 1 could be come rule 5. 

Are you familiar with this?

**Comment by jacobbednarz** [comment]
Other than [implicit and explicit dependencies](https://learn.hashicorp.com/tutorials/terraform/dependencies?in=terraform/0-13), Terraform will apply changes in a maximum parrallelisation approach by walking the resource graph. Here, I suspect a combination of implicit ordering in the API response and Terraform attempting to apply as efficiently as possible, is the cause as to why the apply is running out of order.

**Comment by garrettgalow** [comment]
The default case for using cf-tf to pull firewall rules would be to extract them from the dashboard to use via TF. You cannot set priority in the UI, so the overwhelming majority of cases should have no priorities set. This means the order is implicit based on the API response and we need to set the depends on (like we suggest to do with page rules) to ensure the ordering  is maintained.

I don't think its acceptable to set priorities ourselves since that would be modifying the config which we should avoid as much as possible.

If a customer does have a mix of prioritized and un-prioritized rules then based on what you linked `If not provided, any rules with a priority will be sequenced before those without.` then this process of `depends on` would still be correct, as we should create the prioritized rules first and then the un-prioritized rules (and those should be created in order of the API).

**Comment by jacobbednarz** [comment]
FWIW, page rules also has a similar issue (see cloudflare/terraform-provider-cloudflare#187) where a workaround like this is needed but does cause slow downs and issues in larger codebases.

**Comment by manatarms** [comment]
@jafowler lets make the changes we need in the terraform worker, instead of cf-tf. This might break any assumptions or non standard ways clients might be using cf-tf

**Comment by jacobbednarz** [comment]
Something else you can try here too, is that providing the resources are in the correct order (generated in correct order and outputted), set `-parrallel` in Terraform to 1 and see if it applies in the order you want.

**Pull request closed without merging**
