### PR TITLE
fix test data for cloudflare_bot_management

### PR DESCRIPTION
**Pull request by cwlowder**
The result payload is not supposed to be nested in an array. That was a mistake when I copied over from a different file. Looks like we didn't run the tests before merging to master.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
hmm, that's a good point. it looks like the test suite isn't running nut we haven't made any changes there. I'll have to see why these PRs are different and not triggering it.

**Comment by jacobbednarz** [comment]
ahhhh, I think I see the issue. the branch in the upstream is `master` which has a whole bunch of restrictions against it so CI probably won't run all steps against the `push` operation. I'll keep digging though.

**Comment by cwlowder** [comment]
Would it be better if I update this PR to come from a non-master upstream?

**Comment by jacobbednarz** [comment]
for future, that is a good idea. I'll have a dig into this though as it would be nice to support everything.

**Pull request merged**
