### PR TITLE
Feature/fix cloudflare record when SPF macro used in TXT record

### PR DESCRIPTION
**Pull request by msiherb**
I have added details in the Issue #367 

Please review the fix when you get a chance and advise if anything else needs to be done.

Thank you,

### CODE REVIEW

**Comment by msiherb** [comment]
Terraform reference document : https://www.terraform.io/language/expressions/strings

**Comment by jacobbednarz** [comment]
thanks for raising this PR! before we merge this, can you please add test coverage for the modified behaviour here?

**Comment by reedloden** [comment]
Ran into this same problem, and I can confirm the PR fixes it.

**Comment by jacobbednarz** [comment]
@msiherb do you still want to wrap up this PR? we are still pending a test case here for this added functionality.

**Comment by jacobbednarz** [comment]
#299 has an example of modifying existing functionality and adding test coverage if you'd like to use it as a starting point.

**Comment by msiherb** [comment]
@jacobbednarz ... example you have shared was very helpful. I have followed it and added the tests files for my changes but when run `make test` seeing the following error.
Please advise

```
(⎈ |msiherb)➜  cf-terraforming git:(feature/fix-cloudflare-record-when-spf-macro) ✗ make test 
?       github.com/cloudflare/cf-terraforming/cmd/cf-terraforming       [no test files]
=== RUN   TestGenerate_writeAttrLine
=== RUN   TestGenerate_writeAttrLine/value_is_nil
=== RUN   TestGenerate_writeAttrLine/value_is_list_of_strings
=== RUN   TestGenerate_writeAttrLine/value_is_block_of_strings
=== RUN   TestGenerate_writeAttrLine/value_is_string
=== RUN   TestGenerate_writeAttrLine/value_is_int
=== RUN   TestGenerate_writeAttrLine/value_is_float
=== RUN   TestGenerate_writeAttrLine/value_is_bool
=== RUN   TestGenerate_writeAttrLine/depth_is_0
=== RUN   TestGenerate_writeAttrLine/depth_is_6
--- PASS: TestGenerate_writeAttrLine (0.00s)
    --- PASS: TestGenerate_writeAttrLine/value_is_nil (0.00s)
    --- PASS: TestGenerate_writeAttrLine/value_is_list_of_strings (0.00s)
    --- PASS: TestGenerate_writeAttrLine/value_is_block_of_strings (0.00s)
    --- PASS: TestGenerate_writeAttrLine/value_is_string (0.00s)
    --- PASS: TestGenerate_writeAttrLine/value_is_int (0.00s)
    --- PASS: TestGenerate_writeAttrLine/value_is_float (0.00s)
    --- PASS: TestGenerate_writeAttrLine/value_is_bool (0.00s)
    --- PASS: TestGenerate_writeAttrLine/depth_is_0 (0.00s)
    --- PASS: TestGenerate_writeAttrLine/depth_is_6 (0.00s)
=== RUN   TestGenerate_ResourceNotSupported
time="2022-04-08T10:55:17-07:00" level=fatal msg="failed to detect provider installation"
FAIL    github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd  3.569s
FAIL
make: *** [test] Error 1
(⎈ |msiherb)➜ 
```

**Comment by jacobbednarz** [comment]
the tests still require an initialised Terraform directory. i personally use the `CLOUDFLARE_TERRAFORM_INSTALL_PATH` environment variable to point it at a location i know Terraform is already initialised in. example:

```
$ TESTARGS='-run "^TestResourceGeneration/cloudflare_record" -count 1' CLOUDFLARE_TERRAFORM_INSTALL_PATH="/Users/jacob/src/scratch" make test
?   	github.com/cloudflare/cf-terraforming/cmd/cf-terraforming	[no test files]
=== RUN   TestResourceGeneration
=== RUN   TestResourceGeneration/cloudflare_record_PTR
=== RUN   TestResourceGeneration/cloudflare_record_TXT_SPF
=== RUN   TestResourceGeneration/cloudflare_record_subdomain
=== RUN   TestResourceGeneration/cloudflare_record_CAA
=== RUN   TestResourceGeneration/cloudflare_record_simple
--- PASS: TestResourceGeneration (69.63s)
    --- PASS: TestResourceGeneration/cloudflare_record_PTR (14.33s)
    --- PASS: TestResourceGeneration/cloudflare_record_TXT_SPF (14.39s)
    --- PASS: TestResourceGeneration/cloudflare_record_subdomain (14.18s)
    --- PASS: TestResourceGeneration/cloudflare_record_CAA (12.57s)
    --- PASS: TestResourceGeneration/cloudflare_record_simple (14.15s)
PASS
ok  	github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd	70.013s
```

this is all passing for me locally. thanks for getting this together!

**Pull request merged**
